### ISSUE TITLE
年月日を引数にとるメソッドについて、その型を統一したい

### ISSUE THREAD

**Issue by dogwood008** [J-Quants/jquants-api-client-python#13]
（大変有用な製品の開発・運用をありがとうございます！陰ながら応援させていただきます。）

## 背景

後述の例の通り、始まりと終わりの年月日を引数として要求するメソッドが複数存在する。それらについて、あるものは `datetime` をとり、別のものは `str` をとる。

なお、 `str` の場合、`yyyymmdd` の形式で8桁の数値を `str` で要求する。

### 提案の内容

下記の通り、年月日を要求するメソッドについて、その型を `yyyymmdd` 形式の `str` に統一する事を提案する。

一例として、下記の通り修正のイメージを示す。

https://github.com/J-Quants/jquants-api-client-python/blob/7be06db4cdbc945abfcf375399a9f5752c920471/jquantsapi/client.py#L281-L285

```diff
 def get_price_range( 
     self, 
-     start_dt: datetime = datetime(2017, 1, 1, tzinfo=tz.gettz("Asia/Tokyo")), 
-     end_dt: datetime = datetime.now(tz.gettz("Asia/Tokyo")), 
+     from_yyyymmdd: str = '20170101',
+     to_yyyymmdd_dt: str = None,
 ) -> pd.DataFrame: 
```

### 提案の理由

提案の理由は2つある。

まず1つ目として、型を統一したい理由は、同じ目的で使用する値について、メソッドによって異なる型を要求するのは、混乱の元になるためである。

次に2つ目として、 `datatime` ではなく `str` を選択した理由は、 `datatime` で受け取った値は、 [`pd.date_range()`](https://pandas.pydata.org/docs/reference/api/pandas.date_range.html)に渡されるのみで、他に変換等されていないためである。 

`pd.date_range()` は8桁の数値で `str` を渡しても、 `datetime` と同じように解釈してくれる。このため、引数として受け取った `str` をそのまま `pd.date_range()`  に渡しても動作は変わらないと考えられる。よって、 `datetime` で引数として受け取らなくても、 `str` で必要な情報を得られると考えた。

### 実際の動作

ここで8桁の数値で `str` を渡したときの動作を確認する。以下は、 `pd.date_range()` に対して `yyyymmdd` 形式の8桁の数値で `str` を渡した際の挙動である。

```python
pd.date_range('20220101', '20220214')
# => 
DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
               '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20',
               '2022-01-21', '2022-01-22', '2022-01-23', '2022-01-24',
               '2022-01-25', '2022-01-26', '2022-01-27', '2022-01-28',
               '2022-01-29', '2022-01-30', '2022-01-31', '2022-02-01',
               '2022-02-02', '2022-02-03', '2022-02-04', '2022-02-05',
               '2022-02-06', '2022-02-07', '2022-02-08', '2022-02-09',
               '2022-02-10', '2022-02-11', '2022-02-12', '2022-02-13',
               '2022-02-14'],
              dtype='datetime64[ns]', freq='D')
```

Google colaboratoryでの実行結果：

<img width="538" alt="image" src="https://user-images.githubusercontent.com/2360094/183254194-10a5f6e4-dc52-4889-9c37-fd93fefc16cc.png">

上図より、2022年1月1日から同年2月14日までの範囲を、意図通り取り出せていることがわかる。

### 検討が必要な点

現在 `datetime` として要求するメソッドには、デフォルトと引数としてタイムゾーンが与えられている `datetime` がセットされている。これに特別な理由がある場合は、 `str` を渡すと想定外の挙動を示す可能性がある。

### `str` の箇所

https://github.com/J-Quants/jquants-api-client-python/blob/7be06db4cdbc945abfcf375399a9f5752c920471/jquantsapi/client.py#L229-L231
https://github.com/J-Quants/jquants-api-client-python/blob/7be06db4cdbc945abfcf375399a9f5752c920471/jquantsapi/client.py#L309

### `datetime` の箇所

https://github.com/J-Quants/jquants-api-client-python/blob/7be06db4cdbc945abfcf375399a9f5752c920471/jquantsapi/client.py#L283-L284

https://github.com/J-Quants/jquants-api-client-python/blob/7be06db4cdbc945abfcf375399a9f5752c920471/jquantsapi/client.py#L422-L423

**Comment by hiohiohio** [comment]
Issueをありがとうございます！
メソッドによって日付の指定方法を調整する必要があるのは不便ですね。方針同意です。

対応方針としては文字列型のみを受けるのではなくて、文字列型とdatetime型の両者を受けられるようにできたらうれしいと思いました。(すみません、具体的にどのように実装できるかはまだ検証していません。)

タイムゾーンについては、私が触る環境がUTCを利用していることがおおいので、タイムゾーンをなるべく考慮しておきたいとの考えから設定していますが、現状においては機能としては使用していません。

**Comment by hiohiohio** [comment]
dateutilの
https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.isoparse

**Comment by hiohiohio** [comment]
このモジュールが pandas に依存しているので素直に pandas.Timestamp でよいかもしれませんね。

**Comment by dogwood008** [comment]
ご確認ありがとうございます。
大まかな方針としては合意がとれたかなと思います。追加で、複数の型で受け取れるようにする方針でPRを作ってみます。
