### ISSUE TITLE
feat: support auth_user API endpoint to fetch a refresh token

### ISSUE THREAD

**Issue by hiohiohio** [J-Quants/jquants-api-client-python#20]
J-Quants API に追加される「リフレッシュトークン取得API」に対応したいです。

ref. https://jpx.gitbook.io/j-quants-api/api-reference/refreshtoken

加えて、各種サンプルの更新を実施したいです。
※ サンプル更新については実装の目処がついた段階で別のissueに切り分けますが、一旦はこのissueで管理します。

**Comment by tknhs** [comment]
APIの仕様としてリフレッシュトークンもIDトークンもいつ期限切れになるかをレスポンスに含めて欲しいなと思いました。

**Comment by hiohiohio** [comment]
@tknhs フィードバックをありがとうございます！J-Quants API 運営に伝えました！

**Comment by s-meitoma** [comment]
@tknhs 
コメントありがとうございます！
もう少し詳しく要望を伺いたいのですが、
「いつ期限切れになるかをレスポンスに含めて」というのは、
リフレッシュトークン取得APIをコールした際に、今はresponseにrefreshTokenのみですが、
このresponseにexpiredIn等で期限が切れる日を返せば良いということでしょうか？

```
Returnイメージ
{
    "refreshToken": "xxxxxx",
    "expiredIn": xxxxxxx（何年何月等もしくはUnixTimeを返す）
}
```

**Comment by tknhs** [comment]
@s-meitoma 
> このresponseにexpiredIn等で期限が切れる日を返してほしいということでしょうか？

はい、 `Returnイメージ` に書いていただいた通りの認識で問題ないです。
個人的には `Unixtime` だといろいろ考慮しなくていいなと思ってます。

また、 `expired in` だと切れるまでの時間を表すものになるかなと思いますが、
個人的には切れる日時を表していただくほうが扱いやすいと感じますので `expired at` だと嬉しいです。

**Comment by s-meitoma** [comment]
@tknhs 
ご回答ありがとうございます。
ご要望の意図は承知いたしました。
対応検討し、可能であればAPI内で対応したいと思います。
少々お待ち下さい。

**Comment by hiohiohio** [comment]
ユーザー認証情報とrefresh_tokenを下記の優先順位で取得することを考えています。
既存のサンプルで利用していた `jquantsapi-key.txt` にも対応する方向で考えていますが、落とすかもしれません。

## mail & password

```
Priority: High
1. mail_address & password are supplied as parameters
2. ENV JQUANTS_API_MAIL_ADDRESS & JQUANTS_API_PASSWORD exist
3. mail_address & password exist in ${PWD}/jquants-api.toml if 'google.colab' not in sys.modules else '/content'
4. mail_address & password exist in ${HOME}/.jquants-api/jquants-api.toml if 'google.colab' not in sys.modules else '/content/drive/MyDrive/drive_ws/secret/jquants-api.toml'
Priority: Low
```

## refresh_token

```
Priority: High
1. refresh_token is supplied as a parameter
2. ENV JQUANTS_API_REFRESH_TOKEN exists
3. refresh_token exists in ${PWD}/jquants-api.toml if 'google.colab' not in sys.modules else '/content'
4. refresh_token exists in ${HOME}/.jquants-api/jquants-api.toml if 'google.colab' not in sys.modules else '/content/drive/MyDrive/drive_ws/secret/jquants-api.toml'
5. refresh_token exists in '/content/drive/MyDrive/drive_ws/secret/jquantsapi-key.txt' if 'google.colab' in sys.modules
```

**Comment by hiohiohio** [comment]
既存のサンプルで利用していた `jquantsapi-key.txt` への対応は落としました。
