### ISSUE TITLE
feat: support index endpoint

### ISSUE THREAD

**Issue by hiohiohio** [J-Quants/jquants-api-client-python#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

J-Quants API released the new API endpoint for TOPIX data.
Would like to support this new endpoint.
ref. https://jpx.gitbook.io/j-quants-api/api-reference/indices

**Comment by apokamo** [comment]
# 📐 設計レビュー結果 (再レビュー)

前回の指摘を反映した設計書案を確認しましたが、以下の点について再考・修正が必要です。

## 指摘事項 (Must Fix)
- [ ] **Interface Consistency**: カラム名の命名規則を確認してください。
  - 他のV2エンドポイント（例: `INDICES_BARS_DAILY_COLUMNS`）では `O, H, L, C` なのか `Open, High, Low, Close` なのか。現状の設計書では既存コードとの整合性が不明確です。

## 改善提案 (Should Fix)
- **Error Handling**: 「適切な例外」が具体的に何を指すか（例: `JQuantsAPIError`）を検証観点に含めてください。
- **Type Hinting**: 戻り値の `pd.DataFrame` に含まれるデータの型（datetime64, float64等）についても、検証すべき観点として定義することを推奨します。

## 判定
[ ] Changes Requested (設計修正が必要)
