### ISSUE TITLE
[Bug]: `client.get_listed_info` で上場廃止銘柄を正しく処理できていない

### ISSUE THREAD

**Issue by YusukeSuzuki** [J-Quants/jquants-api-client-python#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

上場廃止銘柄の銘柄コードで `client.get_listed_info()` を使うとクラッシュする。

```
Traceback (most recent call last):
  File "/home/yusuke/garage/finance/stock_analysis/do_filter_by_margins.py", line 64, in <module>
    quants()
  File "/home/yusuke/garage/finance/stock_analysis/do_filter_by_margins.py", line 45, in quants
    info = jqutil.get_listed_info(client, code)
  File "/home/yusuke/garage/finance/stock_analysis/jqutil.py", line 39, in get_listed_info
    df = client.get_listed_info(code)
  File "/home/yusuke/.pyenv/versions/finance/lib/python3.9/site-packages/jquantsapi/client.py", line 371, in get_listed_info
    df.loc[df["Sector33Code"] == "50", "Sector33Code"] = "0050"
  File "/home/yusuke/.pyenv/versions/finance/lib/python3.9/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/yusuke/.pyenv/versions/finance/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'Sector33Code'
```

### Expected Behavior

市場コードに上場廃止に対応するコードを振った上で廃止直前のカテゴリ等を入れておけば良いと思う。

jquants-api 自体が上場廃止を想定していない？

### SDK Version I encountered this issue in

jquants-api-client==0.2.0

### Steps To Reproduce

```markdown
現時点だと銘柄コード `6826` で確認できる。
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by hiohiohio** [comment]
@YusukeSuzuki ご報告いただきありがとうございます！再現確認しました。対応方法検討させてください。

**Comment by hiohiohio** [comment]
```
% curl "https://api.jpx-jquants.com/v1/listed/info?code=6826" -H "Authorization: Bearer $idToken"
{"info": []}
```

**Comment by hiohiohio** [comment]
一時対応で記載していたコードが原因でした。記載場所が正しくなかったことでエラーが発生しています。

https://github.com/J-Quants/jquants-api-client-python/blob/14931955a50d3a236b1a5799f91a69578e187fbf/jquantsapi/client.py#L370-L371

ref. https://github.com/J-Quants/jquants-api-client-python/issues/40

**Comment by hiohiohio** [comment]
問題のあるコードを削除してエラーがでないようにするPRを作成しています。上場廃止銘柄を指定している場合、返り値は空行のデータフレームとなります。
指定した銘柄コードが存在しないのか上場廃止されているかは現状のAPIでは判別が難しい状況であるためこのように対応しています。

**Comment by s-meitoma** [comment]
@YusukeSuzuki 
Issueの起票ありがとうございます！
念の為記載しておきますと、jquants-apiのinfoでは上場廃止等も考慮したものになっております。
そのため、日付指定（20221219）を追加してAPIをコールしていただけると、6826の銘柄は存在しますが、上場廃止となった20221220の場合ですと、返り値なしとなります。

**Comment by YusukeSuzuki** [comment]
素早い対応ありがとうございます。仕様についてもわかりました。
バージョンアップして正しく動いています。
