### ISSUE TITLE
[Bug]:get_prices_daily_quotes()のDate列がdatetime型でなくなった

### ISSUE THREAD

**Issue by kunigaku** [J-Quants/jquants-api-client-python#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

get_prices_daily_quotes()のDate列がdatetime型でなくなった。

### Expected Behavior

get_prices_daily_quotes()のDate列がdatetime型である。

### SDK Version I encountered this issue in

v1.1.0

### Steps To Reproduce

```markdown
df = jqapi.get_prices_daily_quotes(code)
df['Date'].dtype
> dtype('O')
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

https://github.com/J-Quants/jquants-api-client-python/commit/3ab9845d64ef064ef43ea7bd4124467c86938b18#r108375830

**Comment by s-meitoma** [comment]
Issueの起票ありがとうございます。こちら対応させていただきました。
後ほどjquants-api-client v1.1.1としてリリースいたしますので、pip install 等でアップグレードの上、
バグが修正されているかご確認ください。
