### ISSUE TITLE
Relax the requests dependency

### ISSUE THREAD

**Issue by hiohiohio** [J-Quants/jquants-api-client-python#9]
Google Colab でインストールすると以下のエラーが発生しています。
エラーを発生させないために requests のバージョン制約を `^2.23.0` としたいです。

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.28.1 which is incompatible.
Successfully installed jquants-api-client-0.1.0 requests-2.28.1 types-python-dateutil-2.8.19 types-requests-2.28.7 types-urllib3-1.26.20
```

https://github.com/J-Quants/jquants-api-client-python/blob/b879a4c0da64c7425c0bc4a913051a4ad48e8b86/pyproject.toml#L30

**Comment by dakimura** [comment]
https://cocoatomo.github.io/poetry-ja/dependency-specification/
`^2.23.0` だと `<3.0.0` の意味になってしまうので、`~2.23.0` (= `<2.24.0` ) の方がよいですかね？

私もpoetry歴１週間なのでよくわかってないですが、
pyproject.toml書き換えてpoetry updateコマンド打てば良い気がします！

プルリク作ってみました
https://github.com/J-Quants/jquants-api-client-python/pull/10

**Comment by dakimura** [comment]
https://github.com/J-Quants/jquants-api-client-python/pull/10

**Comment by hiohiohio** [comment]
@dakimura ありがとうございます！！
`~2.23.0` だと、例えばですが Python 3.7 環境で 2.28.0 をインストールする際に制約となってしまうため、 
`^2.23.0` でもよいのではと思いましたがいかがでしょうか？

requests の機能的に複雑なことはしていないので、2.23.0 から 2.28.0 まで対応できているのではと推測しています！

**Comment by dakimura** [comment]
なるほどー、修正しました

**Comment by hiohiohio** [comment]
ありがとうございます！
